
Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        end

    config.vm.define "db" do |db|
      db.vm.box = "ubuntu/xenial64"
      db.vm.hostname = "rancher-db"
      db.vm.network "private_network", ip: "192.168.135.10"
      db.vm.synced_folder "~/vbox_shares/image/", "/media/images"
      db.vm.provision "ansible" do |ansible_server|
        ansible_server.playbook = "provision/rancher-db.yml"
      end
    end

    config.vm.define "server" do |server|
      server.vm.box = "ubuntu/xenial64"
      server.vm.hostname = "rancher-server"
      server.vm.network "private_network", ip: "192.168.135.11"
      server.vm.synced_folder "~/vbox_shares/image/", "/media/images"
      server.vm.provision "ansible" do |ansible_server|
        ansible_server.playbook = "provision/rancher-server.yml"
      end
    end

    config.vm.define "host" do |host|
      host.vm.box = "ubuntu/xenial64"
      host.vm.hostname = "rancher-host"
      host.vm.network "private_network", ip: "192.168.135.12"
      host.vm.synced_folder "~/vbox_shares/image/", "/media/images"
      host.vm.provision "ansible" do |ansible_server|
        ansible_server.playbook = "provision/rancher-host.yml"
      end
    end
end
