---
- hosts: host
  become: true
  remote_user: ubuntu
  gather_facts: false
  pre_tasks:
    - name: Bootstrap python
      raw: test -e /usr/bin/python || apt-get update && apt-get -y install python-pip
      changed_when: false
  tasks:
    - name: Get uname
      command: uname -r
      register: uname
    - name: Add apt key for docker
      apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D
    - name: Install docker py
      pip:
        name: "{{ item }}"
      with_items:
        - docker-py
    - name: Copy docker apt sources
      copy:
        src: docker.list
        dest: /etc/apt/sources.list.d/
    - name: Update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install packages
      apt: name={{item}} update_cache=yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - linux-image-extra-{{uname.stdout}}
        - docker-engine
    - name: Add user ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
    - name: Restart docker service
      systemd:
        name: docker
        state: restarted
