---
- hosts: host
  become: true
  remote_user: ubuntu
  gather_facts: false
  pre_tasks:
    - name: Bootstrap python
      raw: test -e /usr/bin/python || apt-get update && apt-get -y install python-pip
      changed_when: false
  tasks:
    - name: Get uname
      command: uname -r
      register: uname
    - name: Add apt key for docker
      apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D
    - name: Install docker py
      pip:
        name: "{{ item }}"
      with_items:
        - docker-py
    - name: Copy docker apt sources
      copy:
        src: docker.list
        dest: /etc/apt/sources.list.d/
    - name: Update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install packages
      apt: name={{item}} update_cache=yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - linux-image-extra-{{uname.stdout}}
        - docker-engine=1.12.6-0~ubuntu-xenial
    - name: Add user ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
    - name: Restart docker service
      systemd:
        name: docker
        state: restarted
    - name: Get IP address of rancher-host
      command: bash -c "getent hosts rancher-host | grep 192 | awk '{print $1}'"
      register: rancherhost
    - name: Get IP address of rancher server
      command: bash -c "getent hosts rancher-server | awk '{print $1}'"
      register: rancherserver
    - name: Get rancher registration token
      uri:
        url: "http://{{rancherserver.stdout}}:8080/v1/projects/1a5/registrationTokens"
        method: GET
      register: ranchertoken
    - name: Pull rancher agent image
      docker_image:
        name: rancher/agent
        tag: v1.2.0
    - name: Add host to rancher
      docker_container:
        name: rancherinitagent
        image: rancher/agent:v1.2.0
        privileged: true
        detach: true
        env:
          CATTLE_AGENT_IP: "{{rancherhost.stdout}}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/rancher:/var/lib/rancher
        command: "{{ranchertoken.json['data'][0]['registrationUrl']}}"
