Vagrant.configure("2") do |config|
  config.vm.box = "mvbcoding/awslinux"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.network 'private_network', type: "dhcp"
  # config.vm.provider "virtualbox" do |vb|
  #    file_to_disk = '/tmp/large_disk.vdi'
  #    unless File.exist?(file_to_disk)
  #      vb.customize ['createhd', '--filename', file_to_disk, '--size', 20 * 1024]
  #    end
  #    vb.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
  # end
end
