
Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        end

    config.vm.define "swarm_mgr" do |swarm_mgr|
      swarm_mgr.vm.box = "ubuntu/xenial64"
      swarm_mgr.vm.hostname = "swarmmgr"
      swarm_mgr.vm.network "private_network", ip: "192.168.135.100"
      swarm_mgr.vm.provision "shell", path: "bootstrap.sh"
    end

    config.vm.define "swarm_node1" do |swarm_node1|
      swarm_node1.vm.box = "ubuntu/xenial64"
      swarm_node1.vm.hostname = "swarmnode1"
      swarm_node1.vm.network "private_network", ip: "192.168.135.101"
      swarm_node1.vm.provision "shell", path: "bootstrap.sh"
    end

    config.vm.define "swarm_node2" do |swarm_node2|
      swarm_node2.vm.box = "ubuntu/xenial64"
      swarm_node2.vm.hostname = "swarmnode2"
      swarm_node2.vm.network "private_network", ip: "192.168.135.102"
      swarm_node2.vm.provision "shell", path: "bootstrap.sh"
    end

    config.vm.define "swarm_node3" do |swarm_node3|
      swarm_node3.vm.box = "ubuntu/xenial64"
      swarm_node3.vm.hostname = "swarmnode3"
      swarm_node3.vm.network "private_network", ip: "192.168.135.103"
      swarm_node3.vm.provision "shell", path: "bootstrap.sh"
    end
end
