
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        end
    config.vm.provision "shell", path: "bootstrap.sh"
    config.vm.network "private_network", type: "dhcp"
    config.vm.synced_folder "~/vbox_shares/httprepo/", "/var/www/html/"
end
