
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        end
    config.vm.provision "shell", path: "bootstrap.sh"
    config.vm.network "private_network", type: "dhcp"
end
